from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict

from data.models.logs import ActionTypeEnum, ResourceTypeEnum


# =====================================================
# BASE SCHEMA (Shared fields, used internally)
# =====================================================
class AuditLogBase(BaseModel):
    username: str = Field(..., max_length=120)
    action: ActionTypeEnum
    resource_type: ResourceTypeEnum
    resource_id: str = Field(..., max_length=120)
    status: str = Field(default="success", max_length=20)
    error_message: Optional[str] = None
    session_id: str = Field(..., max_length=120)


# =====================================================
# CREATE SCHEMA (Used when writing logs)
# =====================================================
class AuditLogCreate(AuditLogBase):
    """
    When writing logs, API/backend will only pass these fields.
    activity_id & timestamp are auto-generated by DB.
    """
    pass


# =====================================================
# RESPONSE SCHEMA (Returned to UI)
# =====================================================
class AuditLogResponse(AuditLogBase):
    id: int
    activity_id: str
    timestamp: datetime

    model_config = ConfigDict(from_attributes=True)


# =====================================================
# OPTIONAL: FILTER REQUEST (For log listing UI)
# =====================================================
class AuditLogFilter(BaseModel):
    username: Optional[str] = None
    action: Optional[ActionTypeEnum] = None
    resource_type: Optional[ResourceTypeEnum] = None
    status: Optional[str] = None

    date_from: Optional[datetime] = None
    date_to: Optional[datetime] = None


# =====================================================
# OPTIONAL: PAGINATED LIST RESPONSE
# =====================================================
class AuditLogList(BaseModel):
    total: int
    page: int
    page_size: int
    results: list[AuditLogResponse]
