"""empty message

Revision ID: 0b3c62343f38
Revises: 
Create Date: 2025-11-02 12:59:12.400997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3c62343f38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APDemand',
    sa.Column('demand_no', sa.String(), nullable=False),
    sa.Column('demand_type', sa.String(length=10), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('fin_year', sa.String(length=10), nullable=False),
    sa.Column('demand_auth', sa.String(length=100), nullable=True),
    sa.Column('depot', sa.String(length=100), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('full_received', sa.Integer(), nullable=True),
    sa.Column('part_received', sa.Integer(), nullable=True),
    sa.Column('outstanding', sa.Integer(), nullable=True),
    sa.Column('percent_received', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('demand_no')
    )
    op.create_table('all_stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_name')
    )
    op.create_table('ledger',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('Ledger_code', sa.Integer(), nullable=False),
    sa.Column('Ledger_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['all_stores.store_id'], ),
    sa.PrimaryKeyConstraint('Ledger_code')
    )
    op.create_table('ledger_maintenance',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ledger_code', sa.Integer(), nullable=False),
    sa.Column('ledger_page', sa.String(length=20), nullable=False),
    sa.Column('ohs_number', sa.String(length=50), nullable=False),
    sa.Column('isg_number', sa.String(length=50), nullable=False),
    sa.Column('ssg_number', sa.String(length=50), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('a_u', sa.String(length=10), nullable=False),
    sa.Column('no_off', sa.Integer(), nullable=False),
    sa.Column('scl_auth', sa.Integer(), nullable=False),
    sa.Column('unsv_stock', sa.Integer(), nullable=False),
    sa.Column('rep_stock', sa.Integer(), nullable=False),
    sa.Column('serv_stock', sa.Integer(), nullable=False),
    sa.Column('msc', sa.Enum('M', 'S', 'C', name='msc_enum'), nullable=False),
    sa.Column('ved', sa.Enum('V', 'E', 'D', name='ved_enum'), nullable=False),
    sa.Column('in_house', sa.Enum('in_house', 'ORD', name='in_house_enum'), nullable=False),
    sa.Column('dues_in', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Integer(), nullable=False),
    sa.Column('bin_number', sa.String(length=50), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('cds_unsv_stock', sa.Integer(), nullable=False),
    sa.Column('cds_rep_stock', sa.Integer(), nullable=False),
    sa.Column('cds_serv_stock', sa.Integer(), nullable=False),
    sa.Column('lpp', sa.String(length=50), nullable=False),
    sa.Column('cos_sec', sa.String(length=50), nullable=False),
    sa.Column('cab_no', sa.String(length=50), nullable=False),
    sa.Column('old_pg_ref', sa.Float(), nullable=False),
    sa.Column('Assy_Comp', sa.String(length=50), nullable=False),
    sa.Column('Re_ord_lvl', sa.Integer(), nullable=False),
    sa.Column('safety_stk', sa.Integer(), nullable=False),
    sa.Column('lpp_dt', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('Rmks', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ledger_code'], ['ledger.Ledger_code'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_maintenance')
    op.drop_table('ledger')
    op.drop_table('all_stores')
    op.drop_table('APDemand')
    # ### end Alembic commands ###
