"""describe your change

Revision ID: 73833b90ee8d
Revises: 9584caadb170
Create Date: 2025-11-02 01:44:23.564985

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73833b90ee8d"
down_revision: str | Sequence[str] | None = "9584caadb170"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Ledger",
        sa.Column("Ledger_name", sa.Integer(), nullable=False),
        sa.Column("Ledger_code", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("Ledger_name", "Ledger_code"),
    )
    op.drop_table("account")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("account_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("account_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("Ledger")
    # ### end Alembic commands ###
