"""apdemand created

Revision ID: 9c1366b6ce6d
Revises: 73833b90ee8d
Create Date: 2025-11-02 02:23:29.206756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1366b6ce6d'
down_revision: Union[str, Sequence[str], None] = '73833b90ee8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APDemand',
    sa.Column('demand_no', sa.String(), nullable=False),
    sa.Column('demand_type', sa.String(length=10), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('fin_year', sa.String(length=10), nullable=False),
    sa.Column('demand_auth', sa.String(length=100), nullable=True),
    sa.Column('depot', sa.String(length=100), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('full_received', sa.Integer(), nullable=True),
    sa.Column('part_received', sa.Integer(), nullable=True),
    sa.Column('outstanding', sa.Integer(), nullable=True),
    sa.Column('percent_received', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('demand_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('APDemand')
    # ### end Alembic commands ###
