"""empty message

Revision ID: ae2e4bc947f8
Revises: 9c1366b6ce6d
Create Date: 2025-11-02 07:06:45.312281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2e4bc947f8'
down_revision: Union[str, Sequence[str], None] = '9c1366b6ce6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_name')
    )
    op.create_table('ledger',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('Ledger_name', sa.Integer(), nullable=False),
    sa.Column('Ledger_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['all_stores.store_id'], ),
    sa.PrimaryKeyConstraint('Ledger_code')
    )
    op.create_table('ledger_maintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ledger_code', sa.String(length=50), nullable=False),
    sa.Column('ledger_page', sa.String(length=20), nullable=False),
    sa.Column('ohs_number', sa.String(length=50), nullable=True),
    sa.Column('isg_number', sa.String(length=50), nullable=True),
    sa.Column('ssg_number', sa.String(length=50), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('a_u', sa.String(length=10), nullable=False),
    sa.Column('no_off', sa.Integer(), nullable=False),
    sa.Column('scl_auth', sa.Integer(), nullable=False),
    sa.Column('unsv_stock', sa.Integer(), nullable=True),
    sa.Column('rep_stock', sa.Integer(), nullable=True),
    sa.Column('serv_stock', sa.Integer(), nullable=True),
    sa.Column('msc', sa.Enum('M', 'S', 'C', name='msc_enum'), nullable=False),
    sa.Column('ved', sa.Enum('V', 'E', 'D', name='ved_enum'), nullable=False),
    sa.Column('in_house', sa.Enum('in_house', 'ORD', name='in_house_enum'), nullable=False),
    sa.Column('dues_in', sa.Integer(), nullable=True),
    sa.Column('consumption', sa.Integer(), nullable=True),
    sa.Column('bin_number', sa.String(length=50), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('cds_unsv_stock', sa.Integer(), nullable=True),
    sa.Column('cds_rep_stock', sa.Integer(), nullable=True),
    sa.Column('cds_serv_stock', sa.Integer(), nullable=True),
    sa.Column('lpp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ledger_code'], ['ledger.Ledger_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ledger',
    sa.Column('Ledger_name', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Ledger_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Ledger_name', 'Ledger_code', name=op.f('Ledger_pkey'))
    )
    op.drop_table('ledger_maintenance')
    op.drop_table('ledger')
    op.drop_table('all_stores')
    # ### end Alembic commands ###
