def clean_json_schema(schema: dict) -> dict:
    """
    Recursively clean a JSON schema generated by Pydantic so it can be used
    as a MongoDB collection validator.

    Removes unsupported or redundant JSON Schema fields and converts types
    to MongoDB's 'bsonType' syntax.

    Args:
        schema (dict): The original Pydantic-generated JSON schema.

    Returns:
        dict: Cleaned schema compatible with MongoDB's $jsonSchema validator.
    """
    if isinstance(schema, dict):
        cleaned = {}
        for key, value in schema.items():
            # Skip unsupported or irrelevant keys for MongoDB validators
            if key in (
                "$defs",
                "$ref",
                "$schema",
                "title",
                "description",
                "default",
                "examples",
            ):
                continue

            # Convert JSON Schema 'type' to MongoDB 'bsonType'
            if key == "type":
                key = "bsonType"
                if value == "integer":
                    value = "int"
                elif value == "number":
                    value = "double"
                elif value == "boolean":
                    value = "bool"
                elif value in ("object", "array", "string", "null"):
                    value = value

            cleaned[key] = clean_json_schema(value)

        return cleaned

    elif isinstance(schema, list):
        return [clean_json_schema(item) for item in schema]

    else:
        return schema
